### PR TITLE
CLOUDP-195920: Document use cases in README

### PR DESCRIPTION
**Pull request by nicohrubec**
## Description

This links to a new HOWTO guide from the Readme, which has instructions and example workflows on how to use the Action.

Link to any related issue(s): [Document use cases in README](https://jira.mongodb.org/browse/CLOUDP-195920)

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)

### CODE REVIEW

**Comment by matt-condon** [comment]
Can we maintain an active list of the supported commands/workflows?

Also could be worth linking to [test.yml](https://github.com/mongodb/atlas-github-action/blob/main/.github/workflows/test.yml) for more example workflows

**Comment by nicohrubec** [comment]
@matt-condon Sure, I linked to the test workflow. Not sure about the wording with the supported commands, because basically we support every non-interactive CLI command, but only a few of them have implementations

**Comment by matt-condon** [comment]
> @matt-condon Sure, I linked to the test workflow. Not sure about the wording with the supported commands, because basically we support every non-interactive CLI command, but only a few of them have implementations

ok sure we can leave that out, thanks!

**Review by matt-condon — APPROVED** [review]
Docs LGTM

**Pull request merged**
