### PR TITLE
Setup of GitHub Action Repository

### PR DESCRIPTION
**Pull request by nicohrubec**
Contains the initial setup of the Repository.

Repository setup:
- basic README with short description and 
- PR and issue templates
- configure dependabot
- remove stale issues
- defining codeowners
- License
- Code of Conduct
- Security.md
- shellcheck

### CODE REVIEW

**Comment by nicohrubec** [comment]
@matt-condon One concern I have is that to test changes we need to dynamically determine the current branch the test workflow is run from and then use that in the uses statement in the test workflow. The problem is that GitHub does not allow that (any dynamic input in the uses statement does not resolve). So the only way to go around this seems to be: https://github.com/orgs/community/discussions/45342#discussioncomment-6790679
This is unfortunately super hacky, so not sure what do here. Would like to hear what you think.

**Comment by matt-condon** [comment]
I had a look at a few other examples of tests run for popular GitHub actions on GH Marketplace and I see a common pattern is `uses: ./`

Have a look at some of the examples here and see if you can find anything slightly more straightforward than that suggested approach: https://github.com/marketplace?type=actions

It shouldn't block this PR anyway, so I'd suggest creating a ticket to investigate
Worst case we can either go with the suggested hack or limiting the PR branches

**Comment by nicohrubec** [comment]
SGTM, missed that before. Will create a ticket to investigate and if it works put it in a follow-up

**Review by matt-condon — APPROVED** [review]
LGTM, thanks for splitting it

**Pull request merged**
